### ISSUE TITLE
Product Options Known Bugs

### ISSUE THREAD

**Issue by WorkshopWeekly** [423s22/G6#9]
- Engrave and other options not operational
- This means no products can be changed with custom other than the variants set up in variant
- This is a link issue from front end and some backend(alyssa's code) to the backend(will's code in variant.js)

**Comment by alyssaerdem** [comment]
Fixed by commits
3857f2e508cf64041c2e30f9f589c9598f975e07
c8c6bdf218e98e488367821752b8ce4f1e5c9426
